<?php

function blocks_settings_block_view_alter(&$data, $block) {
  //dsm($block->delta);
}

function blocks_settings_form_alter(&$form, &$form_state, $form_id) {
  //dsm($form_id);
  if ($form_id == 'blocks_settings_register_team_form') {
    global $user;
    $player_team = blocks_settings_get_player_team($user->uid);
    if (!empty($player_team)) {
      hide($form);
    }
  }
  if ($form_id == 'blocks_settings_tournament_enter_form') {
    dsm($form);
    $form['#submit'][] = 'blocks_settings_tournament_enter';
  }
}

function blocks_settings_tournament_enter($form, &$form_state) {
  dpm($form_state);
}

/*
 * Implement hook_block_info(). 
 */
function blocks_settings_block_info() {
  $blocks = array();
  $blocks['register_team'] = array (
    'info' => t('Register team block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['tournament_enter'] = array (
    'info' => t('Tournament enter'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/*
 * Implement hook_block_view(). 
 */
function blocks_settings_block_view($delta = '') {
  $block = array();
  switch ($delta) {    
    /*Register team*/
    case 'register_team':
      $block['subject'] = '';
      $block['content'] = blocks_settings_register_team_form_callback();
    break;
    /*Tournament enter*/
    case 'tournament_enter':
      $block['subject'] = '';
      $block['content'] = blocks_settings_tournament_enter_form_callback();
    break;
  }
  return $block;
}

function blocks_settings_register_team_form($form, &$form_state) {
  $form['#prefix'] = '<div id="register-team-form">';
  $form['#suffix'] = '</div>';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Зарегистрироваться'),
    '#attributes' => array(
      'class' => array('reg-team'),
    ),
    '#submit' => array('blocks_settings_register_team_form_submit'),
  );
  return $form;
}

function blocks_settings_tournament_enter_form($form, &$form_state) {
  $form['#prefix'] = '<div id="tournament-enter-form">';
  $form['#suffix'] = '</div>';
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Принять участие'),
    '#attributes' => array(
      'class' => array('tournament-enter'),
    ),
    '#submit' => array('blocks_settings_tournament_enter_form_submit'),
    '#validate' => array('blocks_settings_tournament_enter_form_validate'),
    /*'#ajax' => array(
      'callback' => 'blocks_settings_ajax_tournament_enter_form_callback',
      'wrapper' => 'tournament-enter-form',
      'effect' => 'fade',
      'progress' => array('type' => 'none'),
    ),*/
  );
  global $user;
  $uid = $user->uid;
  $form_state['tournament_nid'] = arg(1);
  $form_state['player_uid'] = $uid;
  $tournament_members = blocks_settings_get_tournament_members(arg(1));
  $player_team = blocks_settings_get_player_team($uid);
  foreach ($tournament_members as $key => $value) {
    if ($value->nid == $player_team) {
      $output['intro'] = array(
        '#markup' => '<p class=team-is-registred>Ты уже зарегистрировался!</p>',
      );
      return $output;
    }
  }
  return $form;
}

function blocks_settings_register_team_form_callback() {
  $form = drupal_get_form('blocks_settings_register_team_form');
  $form = drupal_render($form);
  return $form;
}

function blocks_settings_tournament_enter_form_callback() {
  $form = drupal_get_form('blocks_settings_tournament_enter_form');
  $form = drupal_render($form);
  return $form;
}

/*function blocks_settings_ajax_tournament_enter_form_callback($form, &$form_state) {
  return '<p>Регистрация пройдена!</p>';
}*/

function blocks_settings_register_team_form_submit($form, &$form_state) {
  drupal_goto('/node/add/team');
}

function blocks_settings_tournament_enter_form_validate($form, &$form_state) {
  $uid = $form_state['player_uid'];
  $player_team = blocks_settings_get_player_team($uid);
  if (empty($player_team)) {
    variable_set('haddo', 'test');
    form_set_error('submit', t('У тебя нет команды!'));
  }
}

/**
 * Submit for tester_form.
 */
function blocks_settings_tournament_enter_form_submit($form, &$form_state) {
  /*variable_set('haddo', 'test');
  $tournament_nid = $form_state['tournament_nid'];
  blocks_settings_set_tournament_member($tournament_nid, 6);
  //$tournament_members = blocks_settings_get_tournament_members(arg(1));

  //echo 'dsadsa'*/
}

function blocks_settings_get_player_team($uid) {
  $user_team = db_select('field_data_field_team', 'team')  
    ->fields('team', array('field_team_nid'))
    ->condition('team.entity_id', $uid)
    ->execute()
    ->fetchField();
  return $user_team;
}

function blocks_settings_node_view($node) {
}

function blocks_settings_set_tournament_member($tournament_nid, $team_nid) {
  $tournament_node = node_load($tournament_nid);
  $tournament_node->field_members['und'][]['nid'] = $team_nid;
  node_save($tournament_node);
}

function blocks_settings_get_tournament_members($nid) {
  $node_wrapper = entity_metadata_wrapper('node', $nid);
  $tournament_members = $node_wrapper->field_members->value();
  return $tournament_members;
}